[server]
enableCORS = false

[theme]
primaryColor="#F63366"
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#F0F2F6"
textColor="#262730"
font="sans serif"

[client]
toolbarMode = "minimal"

[runner]
# Specify the Python version
pythonVersion = "3.9"